# Generated by Django 5.0.7 on 2024-07-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_chat_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tg_name",
        ),
    ]
