# Generated by Django 5.0.7 on 2024-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название документа"),
                ),
                ("file", models.FileField(upload_to="documents/", verbose_name="файл")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="краткий комментарий к документу",
                        null=True,
                        verbose_name="описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания (записи в БД)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Загружен", "Загружен"),
                            ("Принят", "Принят"),
                            ("Отклонен", "Отклонен"),
                        ],
                        default="Загружен",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "документ",
                "verbose_name_plural": "документы",
                "ordering": ["-pk"],
            },
        ),
    ]
