# Generated by Django 5.0.7 on 2024-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=300, upload_to="documents/", verbose_name="файл"
            ),
        ),
    ]
